---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-kube-admin
  namespace: ci
stringdata:
  admin-password: admin4321
  admin-user: admin
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    jenkins.io/credentials-description: Jenkins Secret - usernamePassword/nexus-kube-artifacts
  labels:
    jenkins.io/credentials-type: usernamePassword
  name: nexus-kube-artifacts
  namespace: ci
stringData:
  password: secrertartifacts
  username: artifacts
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    jenkins.io/credentials-description: Jenkins Secret - usernamePassword/nexus-kube-deployer
  labels:
    jenkins.io/credentials-type: usernamePassword
  name: nexus-kube-deployer
  namespace: ci
stringData:
  password: secretdeployer
  username: deployer
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: nexus-kube-prometheus
  namespace: ci
stringData:
  password: secretprometheus
  username: prometheus
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    name: nexus-kube-tls
  name: nexus-kube-tls
  namespace: ci
stringData:
  tls.crt: |
    insert public key
  tls.key: |
    insert private key
type: Opaque
