---
apiVersion: v1
kind: Service
metadata:
  name: nexus-kube
  namespace: ci
spec:
  ports:
  - name: tcp-8081
    port: 8081
  selector:
    name: nexus-kube
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: scrape-me
  name: exporter-nexus-kube
  namespace: ci
spec:
  ports:
  - name: exporter-9184
    port: 9184
  selector:
    name: nexus-kube
  type: ClusterIP
