apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah-docker-build
  namespace: ci
spec:
  params:
  - default: quay.io/buildah/stable
    description: The location of the buildah builder image.
    name: builderimage
    type: string
  - default: ./Dockerfile
    description: Path to the Dockerfile to build.
    name: dockerfile
    type: string
  - default: ""
    description: Forces FROM in Dockerfile.
    name: fromimage
    type: string
  - default: "true"
    description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS
      registry)
    name: tlsverify
    type: string
  resources:
    inputs:
    - name: source
      type: git
    outputs:
    - name: image
      type: image
  steps:
  - command:
    - /bin/bash
    - -c
    - |
      if echo "$(inputs.params.fromimage)" | grep -E '/.*/' >/dev/null; then \
          sed -i "s|^[ ]*FROM[ ]*[^ ]*$|FROM $(inputs.params.fromimage)|" "$(inputs.params.dockerfile)"; \
      elif test "$(inputs.params.fromimage)"; then \
          sed -i "s|^[ ]*FROM[ ]*[^ ]*$|FROM registry.registry.svc.cluster.local:5000/ci/$(inputs.params.fromimage)|" "$(inputs.params.dockerfile)"; \
      fi
    image: $(inputs.params.builderimage)
    name: patch-from
    resources: {}
    securityContext:
      privileged: true
    workingDir: /workspace/source
  - command:
    - buildah
    - bud
    - --squash
    - --tls-verify=$(inputs.params.tlsverify)
    - --layers
    - -f
    - $(inputs.params.dockerfile)
    - -t
    - $(outputs.resources.image.url)
    - .
    env:
    - name: DO_UPGRADE
      value: "true"
    image: $(inputs.params.builderimage)
    name: build
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/fuse
      name: devfuse
    - mountPath: /var/lib/containers
      name: varlibcontainers
    workingDir: /workspace/source
  - command:
    - buildah
    - push
    - --tls-verify=$(inputs.params.tlsverify)
    - $(outputs.resources.image.url)
    - docker://$(outputs.resources.image.url)
    image: $(inputs.params.builderimage)
    name: push
    resources:
      limits:
        cpu: 400m
        memory: 4Gi
      requests:
        cpu: 200m
        memory: 2Gi
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev/fuse
      name: devfuse
    - mountPath: /var/lib/containers
      name: varlibcontainers
    workingDir: /workspace/source
  volumes:
  - hostPath:
      path: /dev/fuse
    name: devfuse
  - emptyDir: {}
    name: varlibcontainers
