apiVersion: v1
kind: Template
labels:
  app: nexus
  template: nexus-imagestream
metadata:
  annotations:
    description: Nexus - ImageStream
      see https://github.com/faust64/docker-nexus
    iconClass: icon-openshift
    openshift.io/display-name: Nexus
    tags: nexus
  name: nexus-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in Nexus image
    name: nexus
